repos:
-   repo: local
    hooks:
    -   id: generate-lqip
        name: Generate LQIP
        entry: python3 tools/generate_lqip.py
        language: system
        files: ^assets/img/posts/
        exclude: lqip.jpg
        types: [image]
        pass_filenames: true