name:             XerxesDGreat
markdown:         kramdown
title:            i-josh.com
description:      My name is Josh and I support this message
# put your disqus here
disqus_shortname: 
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://i-josh.com

banner:
  images:
  - 'banner/20150709_131530.jpg'
  - 'banner/2015-08-20-11-08-54.jpg'
  - 'banner/20150927_185648.jpg'
  - 'banner/20151017_121848.jpg'
  - 'banner/2014_09_20_04_11_27.jpg'
  - 'banner/2014_09_23_04_16_36.jpg'
  - 'banner/2014_09_27_09_02_02.jpg'
  - 'banner/2014_09_23_04_17_37.jpg'
  - 'banner/2014_09_24_09_07_24.jpg'

# Owner/author information
owner:
  name:           Josh Wickham
  site:           http://i-josh.com
  avatar:         images/home_profile_img_1.jpg
  bio:            "I'm a software engineer who has several joys in life: a great wife, a wonderful daughter, a good job at an exciting startup in San Francisco, woodworking, cooking, and LEGO."
  email:          josh@i-josh.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: josh.wickham # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: XerxesDGreat

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/XerxesDGreat"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/aronbordin"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
  enable: true
  id: "UA-59670577-1"

google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
locale:      en_US
future:      true
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Amount of post to show on home page
# paginate: 5

show_social_sharing: true
enable_facebook_comments: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

defaults:
  -
    scope:
      path: "" # an empty string means the values below apply to all files
    values:
      layout: "blog_post"
  -
    scope:
      path: ""
    values:
      comments: true
  -
    scope:
      path: ""
    values:
      share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true
excerpt_separator: <!-- more -->

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate, jekyll-sitemap]
